### ISSUE TITLE
Compatibility with kotlin 1.4.30

### ISSUE THREAD

**Issue by MrAolen** [ekino/kotlin-quality-plugin#43]
Hello, 

i'm using this library on a kotlin project, but when I upgraded the kotlin version to 1.4.30 I got the following error :

`> Task :ktlintKotlinScriptCheck FAILED
Exception in thread "main" java.lang.NoSuchFieldError: FUN_KEYWORD
        at com.pinterest.ktlint.core.ast.ElementType.<clinit>(ElementType.kt:154)
        at com.pinterest.ktlint.ruleset.standard.ChainWrappingRule.<init>(ChainWrappingRule.kt:36)
        at com.pinterest.ktlint.ruleset.standard.StandardRuleSetProvider.get(StandardRuleSetProvider.kt:11)
        at com.pinterest.ktlint.KtlintCommandLine.loadRulesets(Main.kt:546)
        at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:222)
        at com.pinterest.ktlint.Main.main(Main.kt:62)
`

I think, the ktlint dependency should be updated to v10 ( as shown in this changelog : https://github.com/JLLeitschuh/ktlint-gradle/releases/tag/v10.0.0 )

**Comment by celcius112** [comment]
This must be why it fails when upgrading to Gradle 7 https://github.com/ekino/kotlin-quality-plugin/pull/42

**Comment by clemstoquart** [comment]
@MrAolen You're probably right about ktlint update.

I won't have time to work on this. Feel free to provide a PR.
